export { default as Dashboard } from './Dashboard'
export { default as Schedule } from './Schedule'
export { default as Package } from './Package'
export { default as Member } from './Member'
export { default as Staff } from './Staff'
export { default as Report } from './Report'
export { default as Website } from './Website'
export { Banner, Gallery, Trainer, Testimonial, FAQ, Blog } from './Website' 